### ISSUE TITLE
Warning message from Lavaan

### ISSUE THREAD

**Issue by ricardoV94** [cardiomoon/processR#1]
Whenever I run sem() with model7 or model8 I get this warning:

```
Warning message:
In lavaan::lavaan(model = model, data = model_data, model.type = "sem",  :
  lavaan WARNING: syntax contains parameters involving exogenous covariates; switching to fixed.x = FALSE
```

**Comment by cardiomoon** [comment]
The lastest version of the 'processR' package is on CRAN now.
Please try to install via CRAN in one or two days.
Thank you for your interest.
