### ISSUE TITLE
Shiny app is not working

### ISSUE THREAD

**Issue by PhilipPSimmons** [cardiomoon/processR#11]
Hi,

http://web-r.space:3838/processR <- this URL may not be working anymore. Are you no longer hosting the app? If not, can you provide the code so that it can be run locally? 

Thanks!

**Comment by cardiomoon** [comment]
Please try :

https://cardiomoon.shinyapps.io/processr

Best,

Keon-Woong Moon

2021년 1월 3일 (일) 오전 7:07, PhilipPSimmons <notifications@github.com>님이 작성:

**Comment by PhilipPSimmons** [comment]
This link worked. Thank you!
