### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sforero** [cardiomoon/processR#2]
The following error message appears when installing (using: devtools::install_github("cardiomoon/processR")):
* installing *source* package ‘processR’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so, 6): Library not loaded: /opt/X11/lib/libcairo.2.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/gdtools/libs/gdtools.so
  Reason: image not found
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘processR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/processR’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/kk/y2dgvt6510q0cg9b2kxckztc0000gn/T//RtmpMV2dPL/file4ed7ed7ff3f/processR_0.2.1.2.tar.gz’ had non-zero exit status

**Comment by josh-siegel** [comment]
I have the same issue. Have you found any solution?

**Comment by sforero** [comment]
No, I haven’t found any solution to this.

**Comment by volcalol** [comment]
I also have the same issue.

**Comment by cardiomoon** [comment]
The lastest version(0.2.3) of the 'processR' package is on CRAN now.
Please try to install via CRAN in one or two days.
Thank you for your interest.
