### ISSUE TITLE
Issue installation

### ISSUE THREAD

**Issue by atnplab** [cardiomoon/processR#5]
I have this error when installing processR with devtools

Failed to install 'processR' from GitHub:
  Failed to install 'insight' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/prettyunits/R/prettyunits.rdb' is corrupt
Inoltre: Warning message:
In paste0(" (", pretty_dt(elapsed), ")") :
  internal error -3 in R_decompress1

Any solutions?

Thanks!

**Comment by cardiomoon** [comment]
The lastest version(0.2.3) of the 'processR' package is on CRAN now.
Please try to install via CRAN in one or two days.
Thank you for your interest.
